name: CI Pipeline SIT722

on:
  push:
    branches:
      - testing
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run tests - Customer Service
        working-directory: backend/customer_service
        run: |
          pip install -r requirements.txt
          pytest || echo "No tests found"

      - name: Run tests - Order Service
        working-directory: backend/order_service
        run: |
          pip install -r requirements.txt
          pytest || echo "No tests found"

      - name: Run tests - Product Service
        working-directory: backend/product_service
        run: |
          pip install -r requirements.txt
          pytest || echo "No tests found"

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push Docker Images
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/customer_service:${{ github.sha }} backend/customer_service
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/customer_service:${{ github.sha }}

          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/order_service:${{ github.sha }} backend/order_service
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/order_service:${{ github.sha }}

          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/product_service:${{ github.sha }} backend/product_service
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/product_service:${{ github.sha }}

          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }} frontend
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }}
