name: CI Pipeline

on:
  push:
    branches:
      - testing

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and run tests
        run: |
          pip install -r backend/customer_service/requirements.txt
          pip install -r backend/order_service/requirements.txt
          pip install -r backend/product_service/requirements.txt
          pip install pytest
          pytest backend/customer_service/tests
          pytest backend/order_service/tests
          pytest backend/product_service/tests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login --name <yourACRName>

      - name: Build and Push Docker Images
        run: |
          docker build -t <yourACRName>.azurecr.io/customer-service:latest backend/customer_service
          docker build -t <yourACRName>.azurecr.io/order-service:latest backend/order_service
          docker build -t <yourACRName>.azurecr.io/product-service:latest backend/product_service

          docker push <yourACRName>.azurecr.io/customer-service:latest
          docker push <yourACRName>.azurecr.io/order-service:latest
          docker push <yourACRName>.azurecr.io/product-service:latest
