name: CI Pipeline - Test, Build, and Push

on:
  push:
    branches:
      - testing

jobs:
  test_build_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python for backend services
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install backend test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/customer_service/requirements-dev.txt
        pip install -r backend/order_service/requirements-dev.txt
        pip install -r backend/product_service/requirements-dev.txt

    - name: Run backend tests - customer_service
      run: |
        cd backend/customer_service
        pytest tests

    - name: Run backend tests - order_service
      run: |
        cd backend/order_service
        pytest tests

    - name: Run backend tests - product_service
      run: |
        cd backend/product_service
        pytest tests

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: bajjsit722acr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image for customer_service
      run: |
        docker build -t bajjsit722acr.azurecr.io/customer_service:latest ./backend/customer_service
        docker push bajjsit722acr.azurecr.io/customer_service:latest

    - name: Build and push Docker image for order_service
      run: |
        docker build -t bajjsit722acr.azurecr.io/order_service:latest ./backend/order_service
        docker push bajjsit722acr.azurecr.io/order_service:latest

    - name: Build and push Docker image for product_service
      run: |
        docker build -t bajjsit722acr.azurecr.io/product_service:latest ./backend/product_service
        docker push bajjsit722acr.azurecr.io/product_service:latest

    - name: Build and push Docker image for frontend
      run: |
        docker build -t bajjsit722acr.azurecr.io/frontend:latest ./frontend
        docker push bajjsit722acr.azurecr.io/frontend:latest
