name: Deploy to Production Environment

on:
  push:
    branches:
      - main

jobs:
  deploy_production:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Kubernetes context to production AKS cluster
      run: |
        az aks get-credentials --resource-group bajj-sit722-rg --name bajjsit722aks --overwrite-existing

    - name: Update Kubernetes deployment images
      run: |
        kubectl set image deployment/customer-service customer-service=bajjsit722acr.azurecr.io/customer_service:latest
        kubectl set image deployment/order-service order-service=bajjsit722acr.azurecr.io/order_service:latest
        kubectl set image deployment/product-service product-service=bajjsit722acr.azurecr.io/product_service:latest
        kubectl set image deployment/frontend frontend=bajjsit722acr.azurecr.io/frontend:latest

    - name: Deploy Kubernetes manifests
      run: |
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/ingress.yaml
