name: Deploy to Staging

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Customer Service to ACI
        run: |
          az container create \
            --resource-group bajj-sit722-rg \
            --name customer-staging \
            --image bajjsit722acr.azurecr.io/customer-service:latest \
            --registry-login-server bajjsit722acr.azurecr.io \
            --ip-address Public \
            --dns-name-label customer-staging-722 \
            --ports 80
